"""
dqn_training_visualizations.py

Generates visual reports illustrating the DQN's learning behaviour
throughout training, for project documentation, from a training log CSV
(produced by utils/dqn_logger.py, e.g. evaluation/dqn_training_logs.csv).

Produces 5 figures, one per tracked metric:
  1. Episode Reward   - raw per-episode RL reward, every episode
  2. Average Reward   - the rolling-average column already computed by
                         DQNLogger, smoothing out episode-to-episode noise
  3. Training Loss     - average loss per episode
  4. Epsilon Decay     - exploration rate decay curve
  5. Revenue Trend     - actual dollar revenue per episode - NOT the same
                          as reward in this environment (see
                          pricing_env/reward.py: reward = revenue -
                          discount_penalty - unsold_penalty + balance_bonus)

Each figure is saved as its own PNG under an output directory, ready to
embed directly into project documentation.

Usage
-----
    python -m dashboard.dqn_training_visualizations
    python -m dashboard.dqn_training_visualizations --csv path/to/logs.csv --output-dir path/to/figures
"""

import os
import argparse

import pandas as pd
import matplotlib.pyplot as plt


REQUIRED_COLUMNS = {
    "episode_number", "episode_reward", "average_reward", "revenue",
    "epsilon_value", "training_loss", "replay_buffer_size",
}


def load_training_log(csv_path: str) -> pd.DataFrame:
    """
    Loads a training log CSV (as produced by utils/dqn_logger.py) into a
    DataFrame. Raises a clear error if the file doesn't exist or is
    missing expected columns, rather than failing with a cryptic pandas
    error deep inside a plotting function.
    """
    if not os.path.exists(csv_path):
        raise FileNotFoundError(
            f"Training log not found at '{csv_path}'. "
            f"Run utils/dqn_logger.py first to generate it."
        )

    df = pd.read_csv("dqn_training_logs.csv")

    missing = REQUIRED_COLUMNS - set(df.columns)
    if missing:
        raise ValueError(
            f"Training log at '{csv_path}' is missing expected column(s): {missing}. "
            f"Found columns: {list(df.columns)}. "
            f"If this file was generated by an older version of utils/dqn_logger.py "
            f"(before the 'revenue' column was added), re-run it to regenerate the log."
        )

    return df


def _line_chart(df: pd.DataFrame, column: str, title: str, ylabel: str,
                 color: str, save_path: str) -> bool:
    """
    Shared plotting helper. Returns True if a chart was actually saved,
    False if it was skipped because the column had no real data (e.g.
    epsilon/loss are entirely None when the log came from a random-policy
    self-test rather than real DQN training) - skipping rather than
    saving a blank/misleading chart.
    """
    if df[column].isna().all():
        print(f"  Skipped '{title}': column '{column}' has no data "
              f"(all values are empty - likely a non-training run).")
        return False

    plt.figure(figsize=(9, 5))
    plt.plot(df["episode_number"], df[column], color=color, linewidth=1.2)
    plt.title(title)
    plt.xlabel("Episode")
    plt.ylabel(ylabel)
    plt.grid(True, alpha=0.3)
    plt.tight_layout()
    plt.savefig(save_path, dpi=100)
    plt.close()
    print(f"  Saved: {save_path}")
    return True


def plot_episode_reward(df: pd.DataFrame, output_dir: str) -> str:
    path = os.path.join(output_dir, "episode_reward.png")
    _line_chart(df, "episode_reward", "Episode Reward per Episode",
                "Reward", "#4C72B0", path)
    return path


def plot_average_reward(df: pd.DataFrame, output_dir: str) -> str:
    path = os.path.join(output_dir, "average_reward.png")
    _line_chart(df, "average_reward", "Rolling Average Reward",
                "Average Reward", "#55A868", path)
    return path


def plot_training_loss(df: pd.DataFrame, output_dir: str) -> str:
    path = os.path.join(output_dir, "training_loss.png")
    _line_chart(df, "training_loss", "Training Loss per Episode",
                "Loss (MSE)", "#C44E52", path)
    return path


def plot_epsilon_decay(df: pd.DataFrame, output_dir: str) -> str:
    path = os.path.join(output_dir, "epsilon_decay.png")
    _line_chart(df, "epsilon_value", "Epsilon Decay",
                "Epsilon", "#8172B2", path)
    return path


def plot_revenue_trend(df: pd.DataFrame, output_dir: str) -> str:
    """
    Plots actual dollar revenue per episode. Deliberately a SEPARATE
    chart from Episode Reward - in this environment, reward and revenue
    are genuinely different numbers (reward.py's compute_reward()
    subtracts discount/unsold penalties and adds a pacing bonus on top of
    raw revenue), so plotting revenue tells a different, business-facing
    story than the RL reward curve does.
    """
    path = os.path.join(output_dir, "revenue_trend.png")
    _line_chart(df, "revenue", "Revenue Trend per Episode",
                "Revenue ($)", "#DA8BC3", path)
    return path


def generate_all_figures(csv_path: str, output_dir: str) -> list:
    """
    Loads the training log and generates all 5 figures, saving each as a
    PNG under `output_dir` (created automatically if it doesn't exist).

    Returns
    -------
    list of str
        Paths to every figure that was actually saved (figures skipped
        due to missing data, per `_line_chart`, are not included).
    """
    os.makedirs(output_dir, exist_ok=True)
    df = load_training_log(csv_path)

    print(f"Loaded {len(df)} episodes from '{csv_path}'.")
    print(f"Generating figures into '{output_dir}'...")

    saved_paths = []
    for plot_fn in [
        plot_episode_reward,
        plot_average_reward,
        plot_training_loss,
        plot_epsilon_decay,
        plot_revenue_trend,
    ]:
        path = plot_fn(df, output_dir)
        if os.path.exists(path):
            saved_paths.append(path)

    print(f"\n{len(saved_paths)} of 5 figures generated successfully.")
    return saved_paths


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate DQN training visualizations for project documentation."
    )
    parser.add_argument(
        "--csv", type=str, default="evaluation/dqn_training_logs.csv",
        help="Path to the training log CSV (default: evaluation/dqn_training_logs.csv).",
    )
    parser.add_argument(
        "--output-dir", type=str, default="evaluation/training_figures",
        help="Directory to save figure PNGs into (default: evaluation/training_figures).",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    generate_all_figures(args.csv, args.output_dir)


if __name__ == "__main__":
    main()